######################################################################
# Terms
# AWS_REGION: aws region
# TRAVIS_COMMIT: commit id auto-generated by Travis CI
# REPOSITORY_URL: ECR repository URI
# PRODUCTION_CLUSTER_NAME: name of the running ECS cluster
# PRODUCTION_SERVICE_NAME: name of the running ECS service
#
# Note
# All the aforementioned terms are defined in Travis CI settings,
# except for TRAVIS_COMMIT which is auto-generated by Travis CI.
######################################################################

# The following command lines are push commands for your ECR repository

# login to AWS ECR
$(aws ecr get-login --no-include-email --region ${AWS_REGION})
# Build the docker image
docker build --build-arg CI_COMMIT_SHA=$TRAVIS_COMMIT -t $REPOSITORY_URL:$TRAVIS_COMMIT -t $REPOSITORY_URL:latest .
# Push to an image repository
docker push $REPOSITORY_URL
# Update an AWS ECS service with the new image
# Wait for 20 minutes for deploy
ecs deploy --region ${AWS_REGION} ${PRODUCTION_CLUSTER_NAME} ${PRODUCTION_SERVICE_NAME} --timeout 3000 --tag $TRAVIS_COMMIT --ignore-warnings
